version: '3'
services:
  undershorts:
    image: ghcr.io/masl/undershorts:latest
    container_name: undershorts
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    command: sh -c "redis-server --requirepass PASSWORD --appendonly yes"

  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env
